before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - id: nfpm-default
    package_name: rpkiquery
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Nate Sales
    homepage: https://natesales.net/
    maintainer: Nate Sales <nate@natesales.net>
    description: RPKI query utility
    license: BSD-3
    section: utils
    priority: extra
    formats:
      - deb
      - rpm
publishers:
  - name: fury.io
    ids:
      - nfpm-default
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/natesales/
